export const countryData = {
  "Italy 🇮🇹": [
    "Don't you think pineapple adds a tropical sophistication to pizza? 🍕",
    "Would breaking spaghetti in half make it easier to eat? Let's try! 🍝",
    "Why waste time with espresso when instant coffee exists? It's basically the same! ☕",
    "Isn't Olive Garden basically authentic Italian cuisine? 👨‍🍳",
    "This pasta is good but needs some ketchup to make it perfect! 🍅",
    "Don't you think French wine pairs better with pasta? 🍷",
    "Is pizza really more than just fancy bread with toppings? 🥖",
    "Why not have dinner at 6 PM like normal people? 🕗",
    "Wouldn't a cappuccino go great with this lasagna? 🥪",
    "Isn't gelato just Italian ice cream? Why the fancy name? ❄️"
  ],
  "Japan 🇯🇵": [
    "These house slippers are uncomfortable - mind if I keep my shoes on? 👞",
    "Don't these chopsticks look pretty standing up in the rice? 🍚",
    "Isn't Chinese animation more expressive than anime? 📺",
    "Would adding more soy sauce make this rice less bland? 🍶",
    "Why not mix all the wasabi into the soy sauce at once? 🥢",
    "Isn't karaoke originally Korean? 🎤",
    "What's wrong with blowing my nose at the dinner table? 👃",
    "Don't you think eating while walking saves time? 🚶",
    "Why arrive early when being on time works fine? ⏰",
    "Is sushi really more than just raw fish on rice? 🍣"
  ],
  "France 🇫🇷": [
    "Don't you think American cheese slices have more personality than Brie? 🧀",
    "Would it kill you to put just a few ice cubes in this warm wine? 🍷",
    "Excuse me garçon, can I get some ketchup for my coq au vin? 🍅",
    "Have you ever noticed how British cuisine just has that certain... je ne sais quoi? 🇬🇧",
    "Why do you all eat dinner so late? Are you nocturnal or something? 🕕",
    "These crescent rolls are good - oh sorry, 'croissants' 🥐",
    "Is saying 'bonjour' once a day not enough to show how friendly you are? 👋",
    "Would it ruin the baguette's feng shui if I cut it crosswise? 🥖",
    "Don't you think California wines are more innovative than French ones? 🍇",
    "How can you eat dessert after all that butter in your food? 🍰"
  ],
  "Mexico 🇲🇽": [
    "Isn't Taco Bell basically authentic Mexican food? 🌮",
    "Why do you need so many different types of chilies? Spicy is spicy! 🌶️",
    "Don't you think hard-shell tacos are better than soft ones? 🌯",
    "Is guacamole really worth the extra charge? 🥑",
    "Cinco de Mayo is Mexican Independence Day, right? 🎉",
    "This mild salsa is pretty spicy - how do you eat the hot stuff? 🔥",
    "Why can't you just use shredded cheddar instead of all these Mexican cheeses? 🧀",
    "Don't you think flour tortillas are better than corn ones? 🫓",
    "Is siesta really necessary? Just drink more coffee! ☕",
    "Your abuela's salsa could use some more garlic powder 👵"
  ],
  "India 🇮🇳": [
    "Can I get this curry mild? Like, super mild? No spice at all? 🍛",
    "Isn't naan bread just Indian pizza without toppings? 🫓",
    "Why do you eat with your hands when forks exist? 🍽️",
    "Don't you think butter chicken is the best Indian dish ever? 🍗",
    "Is chai tea latte your national drink? 🫖",
    "How come you don't have any beef dishes on the menu? 🐄",
    "Isn't yoga just fancy stretching? 🧘‍♀️",
    "Why do Indian weddings need to last so many days? 👰",
    "Don't you think Bollywood movies need fewer dance numbers? 💃",
    "Is turmeric really that different from yellow food coloring? 🌾"
  ],
  "Germany 🇩🇪": [
    "How about we skip the bread and just eat the wurst? 🌭",
    "Don't you think German efficiency is a bit overrated? ⚙️",
    "Is Oktoberfest just an excuse to wear leather pants? 🍺",
    "Why so serious all the time? Tell me a German joke! 😐",
    "Wouldn't it be more efficient to have fewer words for everything? 📚",
    "Is following rules really that important? Live a little! 🚦",
    "Don't you think beer should be served ice cold? 🍻",
    "Why do you need so many different types of bread? 🥨",
    "Is punctuality really that important? Time is a social construct! ⏰",
    "Wouldn't cars be more fun without speed limits? 🚗"
  ],
  "Brazil 🇧🇷": [
    "Is soccer really that interesting to watch? ⚽",
    "Don't you think instant coffee is just as good as Brazilian coffee? ☕",
    "Why do you need to dance during every social interaction? 💃",
    "Isn't Carnival just a really long parade? 🎭",
    "Can we speed up this conversation? Why chat for hours? 🗣️",
    "Would you like some ketchup with your feijoada? 🥘",
    "Don't you think Portuguese is just Spanish with different pronunciation? 🗨️",
    "Is Rio really that special? It's just a beach city, right? 🏖️",
    "Why do you need so many ways to prepare coconut? 🥥",
    "Isn't personal space important in your culture? 🤗"
  ],
  "Russia 🇷🇺": [
    "Is vodka really better than a nice fruity cocktail? 🍸",
    "Don't you think it's too cold to eat ice cream in winter? 🍦",
    "Why do you need three names? Isn't one enough? 📝",
    "Wouldn't a smile make your day better? 😊",
    "Is it really necessary to pickle everything? 🥒",
    "Don't you think hot tea in summer is a bit much? 🫖",
    "Why do you call every older woman 'babushka'? 👵",
    "Isn't borscht just fancy beet soup? 🥣",
    "Do you actually enjoy ballet, or is it just for tourists? 💃",
    "How about we skip the soup course just this once? 🍲"
  ],
  "Canada 🇨🇦": [
    "Is maple syrup really that different from corn syrup? 🍁",
    "Don't you think you apologize too much, eh? 🙏",
    "Why do you put gravy and cheese on perfectly good fries? 🧀",
    "Isn't hockey just aggressive ice skating? 🏒",
    "Do you really need to add 'eh' to everything you say? 🗣️",
    "Would it kill you to be a little less polite? 😊",
    "Why is bagged milk a thing? Jugs exist! 🥛",
    "Don't you get tired of Tim Hortons coffee? ☕",
    "Is winter really your favorite season? Really? 🌨️",
    "How about we turn up the heat above 20°C? 🌡️"
  ],
  "South Korea 🇰🇷": [
    "Isn't K-pop just regular pop with prettier people? 🎤",
    "Do you really need 10 steps in your skincare routine? 💆‍♀️",
    "Why do you age differently? Isn't one age enough? 📅",
    "Don't you think Japanese BBQ is better than Korean BBQ? 🥩",
    "Is fan death really a thing? It's just moving air! 💨",
    "Why do you need so many side dishes with every meal? 🍱",
    "Wouldn't it be easier to just use a fork? 🥢",
    "Is kimchi really necessary with EVERY meal? 🥬",
    "Don't you think matching couple outfits are a bit much? 👫",
    "How about we skip the noraebang tonight? 🎤"
  ],
  "Spain 🇪🇸": [
    "Isn't paella just fancy rice? 🥘",
    "Why do you need a nap every afternoon? 😴",
    "Don't you think 10 PM is a bit late for dinner? 🕙",
    "Is running from bulls really a sport? 🐂",
    "Would it kill you to add some spice to your food? 🌶️",
    "Why do you need so many words just to say goodbye? 👋",
    "Don't you think Mexican tapas are better? 🍖",
    "Is flamenco just angry dancing? 💃",
    "Why do you pronounce z and c differently from Latin America? 🗣️",
    "How about we skip the sobremesa and get back to work? ⏰"
  ],
  "Greece 🇬🇷": [
    "Isn't Greek yogurt just thick regular yogurt? 🥛",
    "Do you really need to break plates at every celebration? 🍽️",
    "Why do you need so many columns in your architecture? 🏛️",
    "Don't you think Turkish coffee is better than Greek coffee? ☕",
    "Is feta really necessary on everything? 🧀",
    "Wouldn't it be faster to just say 'no' instead of nodding up? 🤔",
    "Why do all your letters look like math symbols? 📝",
    "Isn't ouzo just spicy water? 🥃",
    "Do you actually enjoy bouzouki music? 🎵",
    "How about we skip the 3-hour lunch today? ⏰"
  ],
  "Sweden 🇸🇪": [
    "Don't you think IKEA furniture is just fancy Lego? 🪑",
    "Is surströmming really food or just a practical joke? 🐟",
    "Why do you need so many different words for snow? ❄️",
    "Wouldn't it be more fun to skip the coffee breaks? ☕",
    "Is personal space really THAT important? 🧍",
    "Don't you think Norwegian meatballs are better? 🍖",
    "Why do you all dress exactly the same? 👕",
    "Is paying with cash still an option? 💳",
    "How about some small talk while waiting for the bus? 🚌",
    "Don't you get tired of being so environmentally conscious? ♻️"
  ],
  "Turkey 🇹🇷": [
    "Is Turkish coffee just coffee with stuff at the bottom? ☕",
    "Don't you think Greek baklava is better? 🍯",
    "Why do you need five daily calls to prayer? ⏰",
    "Isn't evil eye just a fancy blue bead? 🧿",
    "Would you like some milk in your tea? 🫖",
    "Don't you get tired of bargaining for everything? 💰",
    "Is a Turkish bath just a fancy sauna? 🧖",
    "Why do you need so many cats in Istanbul? 🐱",
    "Isn't kebab just fancy grilled meat? 🥩",
    "How about we skip the third tea offering? 🫖"
  ],
  "Vietnam 🇻🇳": [
    "Isn't phở just fancy noodle soup? 🍜",
    "Don't you think chopsticks are less efficient than forks? 🥢",
    "Why do you need so many scooters? 🛵",
    "Would you like some sugar in your Vietnamese coffee? ☕",
    "Is fish sauce really necessary in everything? 🐟",
    "Don't you think bánh mì is just a French sandwich? 🥖",
    "Why do you eat noodle soup for breakfast? 🍜",
    "Isn't Vietnamese coffee too strong? ☕",
    "How about we use a straw instead of spoon and chopsticks? 🥤",
    "Don't you get tired of taking off your shoes everywhere? 👞"
  ],
  "Ireland 🇮🇪": [
    "Is Guinness really better than light beer? 🍺",
    "Don't you think potatoes are overrated? 🥔",
    "Why do you need so many different ways to say 'hello'? 👋",
    "Would it kill you to speak with less slang? 🗣️",
    "Isn't St. Patrick's Day just an excuse to drink? 🍀",
    "Don't you think English breakfast tea is better? 🫖",
    "Why do you need so many types of whiskey? 🥃",
    "Is Irish dancing just aggressive tap dancing? 💃",
    "How about some sun instead of all this rain? ☔",
    "Don't you get tired of telling stories? 📚"
  ],
  "Argentina 🇦🇷": [
    "Isn't Messi just okay? ⚽",
    "Don't you think Brazilian barbecue is better than asado? 🥩",
    "Why do you need to kiss everyone you meet? 😘",
    "Would 11 PM be too early for dinner? 🕙",
    "Is mate really better than regular tea? 🧉",
    "Don't you think tango is just dramatic walking? 💃",
    "Why do you need so many therapists? 🛋️",
    "Isn't dulce de leche just sweet milk? 🍮",
    "How about we speak without using our hands? 🤲",
    "Don't you get tired of claiming everything is from Argentina? 🌎"
  ],
  "Netherlands 🇳🇱": [
    "Is cycling really necessary when you have cars? 🚲",
    "Don't you think your language sounds like German with a cold? 🗣️",
    "Why do you need so many types of cheese? 🧀",
    "Would it kill you to build some hills? ⛰️",
    "Isn't hagelslag just breakfast sprinkles? 🍫",
    "Don't you think Belgian fries are better? 🍟",
    "Why are your buildings so narrow? 🏠",
    "Is going Dutch really necessary on every date? 💶",
    "How about being less direct sometimes? 🤔",
    "Don't you get tired of wearing orange? 👕"
  ],
  "Morocco 🇲🇦": [
    "Is couscous just tiny pasta? 🍝",
    "Don't you think mint tea is too sweet? 🫖",
    "Why do you need so many carpets? 🏺",
    "Would it kill you to give exact directions? 🗺️",
    "Isn't a tagine just a fancy pot? 🍲",
    "Don't you think bargaining is a waste of time? 💰",
    "Why do you need so many spices? 🌶️",
    "Is a hammam just a fancy bath? 🧖",
    "How about we eat with utensils instead of bread? 🥖",
    "Don't you get tired of removing shoes everywhere? 👞"
  ],
  "Singapore 🇸🇬": [
    "Is chewing gum really that bad? 🍬",
    "Don't you think Malaysian food is better? 🍜",
    "Why do you need so many shopping malls? 🛍️",
    "Would it kill you to jaywalk sometimes? 🚶",
    "Isn't Singlish just broken English? 🗣️",
    "Don't you think your food courts are just fancy cafeterias? 🍽️",
    "Why is everything so expensive here? 💰",
    "Is it really that clean, or are you just strict? 🧹",
    "How about we skip the queuing this time? 🧍",
    "Don't you get tired of the air conditioning everywhere? ❄️"
  ],
  "Poland 🇵🇱": [
    "Is pierogi just a fancy dumpling? 🥟",
    "Don't you think German sausages are better? 🌭",
    "Why do you need so many consonants in one word? 📝",
    "Would it kill you to smile at strangers? 😊",
    "Isn't vodka just potato juice? 🥃",
    "Don't you think your language needs more vowels? 🗣️",
    "Why do you put sour cream on everything? 🥛",
    "Is disco polo real music? 🎵",
    "How about some small talk in the elevator? 🛗",
    "Don't you get tired of complaining about the weather? 🌧️"
  ],
  "Egypt 🇪🇬": [
    "Aren't the pyramids just fancy triangles? 🔺",
    "Don't you think Turkish coffee is better than Egyptian? ☕",
    "Why do you need so many cats in ancient art? 🐱",
    "Would it kill you to be on time? ⏰",
    "Isn't koshari just mixed leftovers? 🍚",
    "Don't you think the Sphinx needs a nose job? 🗿",
    "Why do you still use hieroglyphs on everything? 📜",
    "Is shisha just fancy smoking? 💨",
    "How about we skip the third cup of tea? 🫖",
    "Don't you get tired of bargaining for everything? 💰"
  ],
  "South Africa 🇿🇦": [
    "Is braai just another word for BBQ? 🔥",
    "Don't you think 11 official languages is a bit much? 🗣️",
    "Why do you need so many types of biltong? 🥩",
    "Would it kill you to call soccer 'soccer'? ⚽",
    "Isn't a bakkie just a pickup truck? 🚗",
    "Don't you think Australian rules football is better? 🏉",
    "Why do you have so many capital cities? 🏛️",
    "Is rooibos really tea? 🫖",
    "How about we skip the 'just now' and do it now? ⏰",
    "Don't you get tired of having so much sunshine? ☀️"
  ],
} as const;
